local shell = require("shell")

shell.execute("wget -q https://raw.githubusercontent.com/PewPewCricket/oc-link/main/lib/tools/futils.lua /lib/tools/futils.lua")
print("downloaded /lib/tools/futils.lua")
shell.execute("wget -q https://raw.githubusercontent.com/PewPewCricket/oc-link/main/lib/link.lua /lib/link.lua")
print("downloaded /lib/link.lua")
shell.execute("wget -q https://raw.githubusercontent.com/PewPewCricket/oc-link/main/etc/rc.d/link.lua /etc/rc.d/link.lua")
print("downloaded /etc/rc.d/link.lua")
shell.execute("rm /bin/ln.lua")
shell.execute("wget -q https://raw.githubusercontent.com/PewPewCricket/oc-link/main/bin/ln.lua /bin/ln.lua")
print("downloaded /bin/ln.lua")
shell.execute("wget -q https://raw.githubusercontent.com/PewPewCricket/oc-link/main/bin/unlink.lua /bin/unlink.lua")
print("downloaded /bin/unlink.lua")
shell.execute("wget -q https://raw.githubusercontent.com/PewPewCricket/oc-link/main/usr/man/ln /usr/man/ln")
print("downloaded /usr/man/ln")
shell.execute("touch /etc/ln.lst")
shell.execute("rc link enable")
print("link service enabled")
