local shell = require("shell")

shell.execute("mkdir /etc/link.d")
shell.execute("wget -q https://raw.githubusercontent.com/PewPewCricket/oc-link/main/linklib.lua /lib/ld.lua")
print("downloaded /lib/ld.lua")
shell.execute("wget -q https://raw.githubusercontent.com/PewPewCricket/oc-link/main/linkrc.lua /etc/rc.d/ld.lua")
print("downloaded /etc/rc.d/ld.lua")
shell.execute("wget -q https://raw.githubusercontent.com/PewPewCricket/oc-link/main/link.lua /bin/ld.lua")
print("downloaded /bin/ld.lua")
shell.execute("wget -q https://raw.githubusercontent.com/PewPewCricket/oc-link/main/link /usr/man/ld")
print("downloaded /usr/man/ld")
shell.execute("rc ld enable")
