local shell = require("shell")

shell.execute("wget -q https://raw.githubusercontent.com/PewPewCricket/oc-link/main/lib/tools/futils.lua /lib/tools/futils.lua")
print("downloaded /lib/tools/futils.lua")
shell.execute("wget -q https://raw.githubusercontent.com/PewPewCricket/oc-link/main/lib/ld.lua /lib/ld.lua")
print("downloaded /lib/ld.lua")
shell.execute("wget -q https://raw.githubusercontent.com/PewPewCricket/oc-link/main/etc/rc.d/ld.lua /etc/rc.d/ld.lua")
print("downloaded /etc/rc.d/ld.lua")
shell.execute("wget -q https://raw.githubusercontent.com/PewPewCricket/oc-link/main/bin/ld.lua /bin/ld.lua")
print("downloaded /bin/ld.lua")
shell.execute("wget -q https://raw.githubusercontent.com/PewPewCricket/oc-link/main/usr/man/ld /usr/man/ld")
print("downloaded /usr/man/ld")
shell.execute("rc ld enable")
print("ld service enabled")
